### ISSUE TITLE
课表数据抓取字段SCHEDULE_TIME有问题

### ISSUE THREAD

**Issue by dawnBigboy** [FarmerChillax/new-school-sdk#46]
错误信息如下：
\school_sdk\client\api\schedule_parse.py", line 118, in get_class_time
    start_time = self.SCHEDULE_TIME[start]
                 ^^^^^^^^^^^^^^^^^^
AttributeError: 'ScheduleParse' object has no attribute 'SCHEDULE_TIME'

**Comment by dawnBigboy** [comment]
大佬您好，我这边测试抓取个人信息和成绩数据没有问题，但是在抓取课表数据时出现了问题，请您查看一下目前课表的SDK接口是否有问题，另外请问该项目未来有对各个班级课表数据进行统一抓取的规划吗，例如把抓取到的课表数据存储到JSON文件中(可以以班级命名)，这样同个班级的课表数据就不用重复抓取了，谢谢

**Comment by dawnBigboy** [comment]
经过最近排查发现是个别学校的课程时间排列不同导致的问题（例如部分学校一天有14节课，而sdk默认一天10节课则导致了解析错误），我的解决方法是在获取课表的方法中添加schedule_time参数指定课程时间对照列表SCHEDULE_TIME即可正常获取课表数据。

**Comment by FarmerChillax** [comment]
> 这样同个班级的课表数据就不用重复抓取了

同班级不同学生的课本可能是不一样的，这个不能一刀切。并且这种功能应该放在后端程序的缓存中，SDK 不应该做这类的事情。

**Comment by FarmerChillax** [comment]
> 经过最近排查发现是个别学校的课程时间排列不同导致的问题（例如部分学校一天有14节课，而sdk默认一天10节课则导致了解析错误），我的解决方法是在获取课表的方法中添加schedule_time参数指定课程时间对照列表SCHEDULE_TIME即可正常获取课表数据。

`UserClient` 类中有一个 `set_schedule_time` 的方法可以设置不同用户的作息时间

**Comment by dawnBigboy** [comment]
> SCHEDULE_TIME

从结果来看是的，因为抓取个人课表中含有选修等特殊不同课程信息，我原本的意思应该是单独抓取当前学校所有教学班级课表的暑假，而非个人课程表数据，谢谢您的回复！

**Comment by dawnBigboy** [comment]
> > 经过最近排查发现是个别学校的课程时间排列不同导致的问题（例如部分学校一天有14节课，而sdk默认一天10节课则导致了解析错误），我的解决方法是在获取课表的方法中添加schedule_time参数指定课程时间对照列表SCHEDULE_TIME即可正常获取课表数据。
> 
> `UserClient` 类中有一个 `set_schedule_time` 的方法可以设置不同用户的作息时间
> 
> see more:
> 
> https://github.com/FarmerChillax/new-school-sdk/blob/0443f07d55f7df367f38524745749c925707f381/school_sdk/client/__init__.py#L128
> 
> 同样的`get_schedule` 方法也有一个参数可以自行设置：
> 
> https://github.com/FarmerChillax/new-school-sdk/blob/0443f07d55f7df367f38524745749c925707f381/school_sdk/client/__init__.py#L131C1-L132C1

好的，我会结合实际需求进行尝试，谢谢您的帮助！

**Comment by dawnBigboy** [comment]
> > 经过最近排查发现是个别学校的课程时间排列不同导致的问题（例如部分学校一天有14节课，而sdk默认一天10节课则导致了解析错误），我的解决方法是在获取课表的方法中添加schedule_time参数指定课程时间对照列表SCHEDULE_TIME即可正常获取课表数据。
> 
> `UserClient` 类中有一个 `set_schedule_time` 的方法可以设置不同用户的作息时间
> 
> see more:
> 
> https://github.com/FarmerChillax/new-school-sdk/blob/0443f07d55f7df367f38524745749c925707f381/school_sdk/client/__init__.py#L128
> 
> 同样的`get_schedule` 方法也有一个参数可以自行设置：
> 
> https://github.com/FarmerChillax/new-school-sdk/blob/0443f07d55f7df367f38524745749c925707f381/school_sdk/client/__init__.py#L131C1-L132C1

好的，我会结合实际需求进行尝试，谢谢您的帮助！

**Comment by FarmerChillax** [comment]
> 我原本的意思应该是单独抓取当前学校所有教学班级课表的数据，而非个人课程表数据

「班级课表」原本有计划开发，但已经毕业两年了，看起来不会再考虑新功能开发了（也没条件）。欢迎 PR

**Comment by dawnBigboy** [comment]
> > 我原本的意思应该是单独抓取当前学校所有教学班级课表的数据，而非个人课程表数据
> 
> 「班级课表」原本有计划开发，但已经毕业两年了，看起来不会再考虑新功能开发了（也没条件）。欢迎 PR

好的，理解，非常感谢！

**Comment by FarmerChillax** [comment]
看了一下代码，应该是开发到了一半然后就离校了。导致没有开发完这个功能，有兴趣可以考虑补全后 PR
https://github.com/FarmerChillax/new-school-sdk/blob/0443f07d55f7df367f38524745749c925707f381/school_sdk/client/__init__.py#L140
