### ISSUE TITLE
linux云服务器安装部署似乎因为大小问题无法加载到依赖中

### ISSUE THREAD

**Issue by dawnBigboy** [FarmerChillax/new-school-sdk#47]
我在本地window10电脑下载使用sdk之后打算上传到我的云服务器上运行，于是我在服务器的虚拟环境下执行安装pip install school-sdk，但是服务器执行完毕后在没有返回错误信息的情况下再次执行pip list 却没有找到school-sdk这个依赖包，从而导致我的项目无法启动，初步怀疑是因为下载sdk大小受到服务器的ftp服务限制导致的问题（我的sftp最大限制是500MB），所以请问大佬这种情况是sdk的问题还是我的云服务器配置存在问题？
![Snipaste_2024-07-28_23-42-53](https://github.com/user-attachments/assets/d5a19f67-d339-4704-bc4c-6fea7b4d0d8a)

**Comment by FarmerChillax** [comment]
这个问题是因为「机器内存不足」导致，README 中有提到解决方法: `pip --no-cache-dir install school-sdk`  

ref: https://github.com/FarmerChillax/new-school-sdk/blob/0443f07d55f7df367f38524745749c925707f381/README.md?plain=1#L50

**Comment by dawnBigboy** [comment]
> 这个问题是因为「机器内存不足」导致（为了解决验证码自动识别引入了 PyTorch），README 中有提到解决方法: `pip --no-cache-dir install school-sdk`
> 
> ref:
> 
> https://github.com/FarmerChillax/new-school-sdk/blob/0443f07d55f7df367f38524745749c925707f381/README.md?plain=1#L50

好的，非常感谢
